@api = http://192.168.0.35:8080

###
GET {{api}}/user/7

### 
POST {{api}}/users/5/tasks
Accept: application/json
Content-Type: application/json

{
        "title": "Grocery Shopping",
        "status": true,
        "date": "2025-03-27",
        "time": "10:00:00",
        "priority": "medium",
        "description": "Buy groceries for the week",
        "emoji": "🛒",
        "user_id": 8,
        "categories": [20, 8]
}

###
PUT {{api}}users/5/tasks/150
Accept: application/json
Content-Type: application/json

{
    "title": "Run Every Morning",
    "status": false,
    "date": "2025-03-25",
    "time": "07:00:00",
    "priority": "high",
    "description": "Run for 20 minutes",
    "emoji": "🦵",
    "user_id": 1,
    "categories": [1,5,18]
}

###
DELETE  {{api}}/task/21
Accept: application/json
Content-Type: application/json